#!/usr/bin/env bash
pipeline {
    agent any
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }
    environment {
        CC = 'dodo'
        // paramKey = credentials("${env.TEST_USER}")
        // paramKey2 = credentials("${env.DODO_LIHAO}")
        credentials = credentials("${TEST_USER}")
        credentials2 = credentials("${DODO_LIHAO}")
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'

                echo "sth is --- ${CC}"
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                echo "credentials is --- ${credentials}"
                echo "credentials2 is --- ${credentials2}"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
