#!/usr/bin/env bash
pipeline {
    agent any
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }
    environment {
        CC = 'dodo'
        credentials = credentials("${env.STR_USER}")
//        echo 'environment ..'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                
                echo "sth is --- ${CC}"
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                echo "credentials is --- ${credentials}"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}